### ISSUE TITLE
Use classes instead of CSS properties

### ISSUE THREAD

**Issue by sularome** [lukasztom5/Portfolio_JS_CSS_HTML#1]
A better practice to style errors in JS is to use classes instead of setting specific CSS properties. For example here you set exact properties:
```
 panelWynikowy.style.display = "block";
                        inputOd.style.border="4px solid red";
                        inputDo.style.border="4px solid red";
                        wynik.innerHTML = "Jednostka wejściowa jest taka sama jak wyjściowa";
```

A better practice would be to create a CSS class with those properties and then add the class to the element when there is an error:

```CSS
.error{
    display: block;
}
.error input{
    border: "4px solid red"
}
```
And then when you have error
```JS
panelWynikowy.classList.add('error');
```

This way you have clearly separated styles from JS and can change look without touching the JS.

**Comment by lukasztom5** [comment]
Add CSS selectors for 'error class and 'correct' class in CSS file. Replaced elements with .style. into classList.add(). Removed all JS lines with .style.
